# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  trackmngmtmeetings:
    image: trackmngmtmeetings
    build:
      context: .
      dockerfile: TrackMngmtMeetings/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5240:5240
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
